### ISSUE TITLE
No defaults for Rust parametric features

### ISSUE THREAD

**Issue by anlava** [light-curve/light-curve-python#194]
Default values for keyword arguments aren't used while calling Rust meta-features, whilst in Python it is, which looks inconsistent.

`TypeError: MedianBufferRangePercentage.__new__() missing 1 required positional argument: 'quantile'`

**Comment by hombit** [comment]
Thank you for reporting it! I believe you are talking about parametric features, not meta-features like `Bins` or `Periodogram`. Most of parametric feature constructors, including `MedianBufferRangePercentage` currently accept both positional and keyword-only arguments. However you are right that they don't have default values and this is inconsistent with Python implementation.

**Comment by anlava** [comment]
Yes, sorry, I meant parametric features =)
