### ISSUE TITLE
Minimal python version is wrong

### ISSUE THREAD

**Issue by erusseil** [light-curve/light-curve-python#269]
Requirement for iminuit version implies a minimum python version of 3.8
Readme should be updated

**Comment by hombit** [comment]
It actually says it in this section:
https://github.com/light-curve/light-curve-python#rainbow-fit

It also reflected in `pyproject.toml`:
https://github.com/light-curve/light-curve-python/blob/5016c92bbc7d6161d39f70a92f19d3518b2c5dd6/light-curve/pyproject.toml#L36-L37

Please feel free to PR any change you think would work better
